hard_tabs = true
blank_lines_lower_bound = 0
blank_lines_upper_bound = 10
fn_single_line = true
max_width = 80
fn_call_width = 60
format_generated_files = false
imports_granularity = "Item"
group_imports = "One"
imports_layout = "Vertical"
overflow_delimited_expr = true
use_field_init_shorthand = true
