set windows-shell := ["C:/tools/cygwin/bin/sh.exe","-c"]
set positional-arguments

# forky_esp
sh := 'C:/tools/cygwin/bin/'
backtrace := '0'
# backtrace := '1'
# backtrace := 'full'

default:
	just --list

# run example:
# 	RUST_BACKTRACE={{backtrace}} cargo run --example {{example}} --target wasm32-unknown-unknown

# run-w *args:
# 	just watch 'just run {{args}}'

build example:
	cargo build --example {{example}} --release --target wasm32-unknown-unknown
	RUST_BACKTRACE={{backtrace}} wasm-bindgen \
	--out-dir ./html/wasm \
	--out-name bindgen \
	--target web \
	./target/wasm32-unknown-unknown/release/examples/{{example}}.wasm
# --no-typescript \

build-w *args:
	just watch 'just build {{args}}'

serve:
	cd ./html && live-server
serve-https:
	cd ./html && live-server --https=https.config.js

clean:
	cargo clean
	rm -rf ./target
	rm -rf ./Cargo.lock

@log argument:
	echo {{argument}}

publish:
	cargo publish --allow-dirty

watch command:
	cargo watch -q --ignore '{**/mod.rs,justfile,.gitignore}' --ignore '**.{txt,md,wasm,wat}' --ignore '{html/wasm,target/}' -- {{command}}


ssl:
	openssl genrsa -out target/client-key.pem 2048
	openssl req -new -key target/client-key.pem -subj "/CN=$cn\/emailAddress=admin@$cn/C=US/ST=Ohio/L=Columbus/O=Widgets Inc/OU=Some Unit" -out target/client.csr
	openssl x509 -req -in target/client.csr -signkey target/client-key.pem -out target/client-cert.pem