use strum::IntoEnumIterator;
use strum_macros::{EnumCount, EnumIter};

use crate::tarot::TarotCard;


#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, EnumIter, EnumCount)]
pub enum TarotCardEnum {
	TheFool,
	TheMagician,
	TheHighPriestess,
	TheEmpress,
	TheEmperor,
	TheHierophant,
	TheLovers,
	TheChariot,
	Strength,
	TheHermit,
	TheWheelOfFortune,
	Justice,
	TheHangedMan,
	Death,
	Temperance,
	TheDevil,
	TheTower,
	TheStar,
	TheMoon,
	TheSun,
	Judgement,
	TheWorld,
	AceOfWands,
	TwoOfWands,
	ThreeOfWands,
	FourOfWands,
	FiveOfWands,
	SixOfWands,
	SevenOfWands,
	EightOfWands,
	NineOfWands,
	TenOfWands,
	PageOfWands,
	KnightOfWands,
	QueenOfWands,
	KingOfWands,
	AceOfCups,
	TwoOfCups,
	ThreeOfCups,
	FourOfCups,
	FiveOfCups,
	SixOfCups,
	SevenOfCups,
	EightOfCups,
	NineOfCups,
	TenOfCups,
	PageOfCups,
	KnightOfCups,
	QueenOfCups,
	KingOfCups,
	AceOfSwords,
	TwoOfSwords,
	ThreeOfSwords,
	FourOfSwords,
	FiveOfSwords,
	SixOfSwords,
	SevenOfSwords,
	EightOfSwords,
	NineOfSwords,
	TenOfSwords,
	PageOfSwords,
	KnightOfSwords,
	QueenOfSwords,
	KingOfSwords,
	AceOfPentacles,
	TwoOfPentacles,
	ThreeOfPentacles,
	FourOfPentacles,
	FiveOfPentacles,
	SixOfPentacles,
	SevenOfPentacles,
	EightOfPentacles,
	NineOfPentacles,
	TenOfPentacles,
	PageOfPentacles,
	KnightOfPentacles,
	QueenOfPentacles,
	KingOfPentacles,
}


impl Into<usize> for &TarotCardEnum {
	fn into(self) -> usize { *self as usize }
}
impl Into<usize> for TarotCardEnum {
	fn into(self) -> usize { self as usize }
}

impl TryFrom<usize> for TarotCardEnum {
	type Error = ();

	fn try_from(value: usize) -> Result<Self, Self::Error> {
		Self::iter().nth(value).ok_or(())
	}
}
impl From<TarotCardEnum> for TarotCard {
	fn from(value: TarotCardEnum) -> Self {
		value.into()
	}
}

impl From<&TarotCardEnum> for TarotCard {
	fn from(value: &TarotCardEnum) -> Self {
		match value {
			TarotCardEnum::TheFool => TarotCard::THE_FOOL,
			TarotCardEnum::TheMagician => TarotCard::THE_MAGICIAN,
			TarotCardEnum::TheHighPriestess => TarotCard::THE_HIGH_PRIESTESS,
			TarotCardEnum::TheEmpress => TarotCard::THE_EMPRESS,
			TarotCardEnum::TheEmperor => TarotCard::THE_EMPEROR,
			TarotCardEnum::TheHierophant => TarotCard::THE_HIEROPHANT,
			TarotCardEnum::TheLovers => TarotCard::THE_LOVERS,
			TarotCardEnum::TheChariot => TarotCard::THE_CHARIOT,
			TarotCardEnum::Strength => TarotCard::STRENGTH,
			TarotCardEnum::TheHermit => TarotCard::THE_HERMIT,
			TarotCardEnum::TheWheelOfFortune => TarotCard::THE_WHEEL_OF_FORTUNE,
			TarotCardEnum::Justice => TarotCard::JUSTICE,
			TarotCardEnum::TheHangedMan => TarotCard::THE_HANGED_MAN,
			TarotCardEnum::Death => TarotCard::DEATH,
			TarotCardEnum::Temperance => TarotCard::TEMPERANCE,
			TarotCardEnum::TheDevil => TarotCard::THE_DEVIL,
			TarotCardEnum::TheTower => TarotCard::THE_TOWER,
			TarotCardEnum::TheStar => TarotCard::THE_STAR,
			TarotCardEnum::TheMoon => TarotCard::THE_MOON,
			TarotCardEnum::TheSun => TarotCard::THE_SUN,
			TarotCardEnum::Judgement => TarotCard::JUDGMENT,
			TarotCardEnum::TheWorld => TarotCard::THE_WORLD,
			TarotCardEnum::AceOfWands => TarotCard::ACE_OF_WANDS,
			TarotCardEnum::TwoOfWands => TarotCard::TWO_OF_WANDS,
			TarotCardEnum::ThreeOfWands => TarotCard::THREE_OF_WANDS,
			TarotCardEnum::FourOfWands => TarotCard::FOUR_OF_WANDS,
			TarotCardEnum::FiveOfWands => TarotCard::FIVE_OF_WANDS,
			TarotCardEnum::SixOfWands => TarotCard::SIX_OF_WANDS,
			TarotCardEnum::SevenOfWands => TarotCard::SEVEN_OF_WANDS,
			TarotCardEnum::EightOfWands => TarotCard::EIGHT_OF_WANDS,
			TarotCardEnum::NineOfWands => TarotCard::NINE_OF_WANDS,
			TarotCardEnum::TenOfWands => TarotCard::TEN_OF_WANDS,
			TarotCardEnum::PageOfWands => TarotCard::PAGE_OF_WANDS,
			TarotCardEnum::KnightOfWands => TarotCard::KNIGHT_OF_WANDS,
			TarotCardEnum::QueenOfWands => TarotCard::QUEEN_OF_WANDS,
			TarotCardEnum::KingOfWands => TarotCard::KING_OF_WANDS,
			TarotCardEnum::AceOfCups => TarotCard::ACE_OF_CUPS,
			TarotCardEnum::TwoOfCups => TarotCard::TWO_OF_CUPS,
			TarotCardEnum::ThreeOfCups => TarotCard::THREE_OF_CUPS,
			TarotCardEnum::FourOfCups => TarotCard::FOUR_OF_CUPS,
			TarotCardEnum::FiveOfCups => TarotCard::FIVE_OF_CUPS,
			TarotCardEnum::SixOfCups => TarotCard::SIX_OF_CUPS,
			TarotCardEnum::SevenOfCups => TarotCard::SEVEN_OF_CUPS,
			TarotCardEnum::EightOfCups => TarotCard::EIGHT_OF_CUPS,
			TarotCardEnum::NineOfCups => TarotCard::NINE_OF_CUPS,
			TarotCardEnum::TenOfCups => TarotCard::TEN_OF_CUPS,
			TarotCardEnum::PageOfCups => TarotCard::PAGE_OF_CUPS,
			TarotCardEnum::KnightOfCups => TarotCard::KNIGHT_OF_CUPS,
			TarotCardEnum::QueenOfCups => TarotCard::QUEEN_OF_CUPS,
			TarotCardEnum::KingOfCups => TarotCard::KING_OF_CUPS,
			TarotCardEnum::AceOfSwords => TarotCard::ACE_OF_SWORDS,
			TarotCardEnum::TwoOfSwords => TarotCard::TWO_OF_SWORDS,
			TarotCardEnum::ThreeOfSwords => TarotCard::THREE_OF_SWORDS,
			TarotCardEnum::FourOfSwords => TarotCard::FOUR_OF_SWORDS,
			TarotCardEnum::FiveOfSwords => TarotCard::FIVE_OF_SWORDS,
			TarotCardEnum::SixOfSwords => TarotCard::SIX_OF_SWORDS,
			TarotCardEnum::SevenOfSwords => TarotCard::SEVEN_OF_SWORDS,
			TarotCardEnum::EightOfSwords => TarotCard::EIGHT_OF_SWORDS,
			TarotCardEnum::NineOfSwords => TarotCard::NINE_OF_SWORDS,
			TarotCardEnum::TenOfSwords => TarotCard::TEN_OF_SWORDS,
			TarotCardEnum::PageOfSwords => TarotCard::PAGE_OF_SWORDS,
			TarotCardEnum::KnightOfSwords => TarotCard::KNIGHT_OF_SWORDS,
			TarotCardEnum::QueenOfSwords => TarotCard::QUEEN_OF_SWORDS,
			TarotCardEnum::KingOfSwords => TarotCard::KING_OF_SWORDS,
			TarotCardEnum::AceOfPentacles => TarotCard::ACE_OF_PENTACLES,
			TarotCardEnum::TwoOfPentacles => TarotCard::TWO_OF_PENTACLES,
			TarotCardEnum::ThreeOfPentacles => TarotCard::THREE_OF_PENTACLES,
			TarotCardEnum::FourOfPentacles => TarotCard::FOUR_OF_PENTACLES,
			TarotCardEnum::FiveOfPentacles => TarotCard::FIVE_OF_PENTACLES,
			TarotCardEnum::SixOfPentacles => TarotCard::SIX_OF_PENTACLES,
			TarotCardEnum::SevenOfPentacles => TarotCard::SEVEN_OF_PENTACLES,
			TarotCardEnum::EightOfPentacles => TarotCard::EIGHT_OF_PENTACLES,
			TarotCardEnum::NineOfPentacles => TarotCard::NINE_OF_PENTACLES,
			TarotCardEnum::TenOfPentacles => TarotCard::TEN_OF_PENTACLES,
			TarotCardEnum::PageOfPentacles => TarotCard::PAGE_OF_PENTACLES,
			TarotCardEnum::KnightOfPentacles => TarotCard::KNIGHT_OF_PENTACLES,
			TarotCardEnum::QueenOfPentacles => TarotCard::QUEEN_OF_PENTACLES,
			TarotCardEnum::KingOfPentacles => TarotCard::KING_OF_PENTACLES,
		}
	}
}

impl Into<TarotCardEnum> for &TarotCard {
	fn into(self) -> TarotCardEnum {
		match *self {
			TarotCard::THE_FOOL => TarotCardEnum::TheFool,
			TarotCard::THE_MAGICIAN => TarotCardEnum::TheMagician,
			TarotCard::THE_HIGH_PRIESTESS => TarotCardEnum::TheHighPriestess,
			TarotCard::THE_EMPRESS => TarotCardEnum::TheEmpress,
			TarotCard::THE_EMPEROR => TarotCardEnum::TheEmperor,
			TarotCard::THE_HIEROPHANT => TarotCardEnum::TheHierophant,
			TarotCard::THE_LOVERS => TarotCardEnum::TheLovers,
			TarotCard::THE_CHARIOT => TarotCardEnum::TheChariot,
			TarotCard::STRENGTH => TarotCardEnum::Strength,
			TarotCard::THE_HERMIT => TarotCardEnum::TheHermit,
			TarotCard::THE_WHEEL_OF_FORTUNE => TarotCardEnum::TheWheelOfFortune,
			TarotCard::JUSTICE => TarotCardEnum::Justice,
			TarotCard::THE_HANGED_MAN => TarotCardEnum::TheHangedMan,
			TarotCard::DEATH => TarotCardEnum::Death,
			TarotCard::TEMPERANCE => TarotCardEnum::Temperance,
			TarotCard::THE_DEVIL => TarotCardEnum::TheDevil,
			TarotCard::THE_TOWER => TarotCardEnum::TheTower,
			TarotCard::THE_STAR => TarotCardEnum::TheStar,
			TarotCard::THE_MOON => TarotCardEnum::TheMoon,
			TarotCard::THE_SUN => TarotCardEnum::TheSun,
			TarotCard::JUDGMENT => TarotCardEnum::Judgement,
			TarotCard::THE_WORLD => TarotCardEnum::TheWorld,
			TarotCard::ACE_OF_WANDS => TarotCardEnum::AceOfWands,
			TarotCard::TWO_OF_WANDS => TarotCardEnum::TwoOfWands,
			TarotCard::THREE_OF_WANDS => TarotCardEnum::ThreeOfWands,
			TarotCard::FOUR_OF_WANDS => TarotCardEnum::FourOfWands,
			TarotCard::FIVE_OF_WANDS => TarotCardEnum::FiveOfWands,
			TarotCard::SIX_OF_WANDS => TarotCardEnum::SixOfWands,
			TarotCard::SEVEN_OF_WANDS => TarotCardEnum::SevenOfWands,
			TarotCard::EIGHT_OF_WANDS => TarotCardEnum::EightOfWands,
			TarotCard::NINE_OF_WANDS => TarotCardEnum::NineOfWands,
			TarotCard::TEN_OF_WANDS => TarotCardEnum::TenOfWands,
			TarotCard::PAGE_OF_WANDS => TarotCardEnum::PageOfWands,
			TarotCard::KNIGHT_OF_WANDS => TarotCardEnum::KnightOfWands,
			TarotCard::QUEEN_OF_WANDS => TarotCardEnum::QueenOfWands,
			TarotCard::KING_OF_WANDS => TarotCardEnum::KingOfWands,
			TarotCard::ACE_OF_CUPS => TarotCardEnum::AceOfCups,
			TarotCard::TWO_OF_CUPS => TarotCardEnum::TwoOfCups,
			TarotCard::THREE_OF_CUPS => TarotCardEnum::ThreeOfCups,
			TarotCard::FOUR_OF_CUPS => TarotCardEnum::FourOfCups,
			TarotCard::FIVE_OF_CUPS => TarotCardEnum::FiveOfCups,
			TarotCard::SIX_OF_CUPS => TarotCardEnum::SixOfCups,
			TarotCard::SEVEN_OF_CUPS => TarotCardEnum::SevenOfCups,
			TarotCard::EIGHT_OF_CUPS => TarotCardEnum::EightOfCups,
			TarotCard::NINE_OF_CUPS => TarotCardEnum::NineOfCups,
			TarotCard::TEN_OF_CUPS => TarotCardEnum::TenOfCups,
			TarotCard::PAGE_OF_CUPS => TarotCardEnum::PageOfCups,
			TarotCard::KNIGHT_OF_CUPS => TarotCardEnum::KnightOfCups,
			TarotCard::QUEEN_OF_CUPS => TarotCardEnum::QueenOfCups,
			TarotCard::KING_OF_CUPS => TarotCardEnum::KingOfCups,
			TarotCard::ACE_OF_SWORDS => TarotCardEnum::AceOfSwords,
			TarotCard::TWO_OF_SWORDS => TarotCardEnum::TwoOfSwords,
			TarotCard::THREE_OF_SWORDS => TarotCardEnum::ThreeOfSwords,
			TarotCard::FOUR_OF_SWORDS => TarotCardEnum::FourOfSwords,
			TarotCard::FIVE_OF_SWORDS => TarotCardEnum::FiveOfSwords,
			TarotCard::SIX_OF_SWORDS => TarotCardEnum::SixOfSwords,
			TarotCard::SEVEN_OF_SWORDS => TarotCardEnum::SevenOfSwords,
			TarotCard::EIGHT_OF_SWORDS => TarotCardEnum::EightOfSwords,
			TarotCard::NINE_OF_SWORDS => TarotCardEnum::NineOfSwords,
			TarotCard::TEN_OF_SWORDS => TarotCardEnum::TenOfSwords,
			TarotCard::PAGE_OF_SWORDS => TarotCardEnum::PageOfSwords,
			TarotCard::KNIGHT_OF_SWORDS => TarotCardEnum::KnightOfSwords,
			TarotCard::QUEEN_OF_SWORDS => TarotCardEnum::QueenOfSwords,
			TarotCard::KING_OF_SWORDS => TarotCardEnum::KingOfSwords,
			TarotCard::ACE_OF_PENTACLES => TarotCardEnum::AceOfPentacles,
			TarotCard::TWO_OF_PENTACLES => TarotCardEnum::TwoOfPentacles,
			TarotCard::THREE_OF_PENTACLES => TarotCardEnum::ThreeOfPentacles,
			TarotCard::FOUR_OF_PENTACLES => TarotCardEnum::FourOfPentacles,
			TarotCard::FIVE_OF_PENTACLES => TarotCardEnum::FiveOfPentacles,
			TarotCard::SIX_OF_PENTACLES => TarotCardEnum::SixOfPentacles,
			TarotCard::SEVEN_OF_PENTACLES => TarotCardEnum::SevenOfPentacles,
			TarotCard::EIGHT_OF_PENTACLES => TarotCardEnum::EightOfPentacles,
			TarotCard::NINE_OF_PENTACLES => TarotCardEnum::NineOfPentacles,
			TarotCard::TEN_OF_PENTACLES => TarotCardEnum::TenOfPentacles,
			TarotCard::PAGE_OF_PENTACLES => TarotCardEnum::PageOfPentacles,
			TarotCard::KNIGHT_OF_PENTACLES => TarotCardEnum::KnightOfPentacles,
			TarotCard::QUEEN_OF_PENTACLES => TarotCardEnum::QueenOfPentacles,
			TarotCard::KING_OF_PENTACLES => TarotCardEnum::KingOfPentacles,
		}
	}
}
