[target.x86_64-unknown-linux-gnu]
# note: mold and clang must be installed: sudo apt install mold clang
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"