# requires powershell because of CMAKE_OBJECT_PATH_MAX
set shell := ["powershell.exe", "-c"]
port := 'COM3'
backtrace := '1'
# target-idf := '--target riscv32imc-esp-espidf "-Zbuild-std=std,panic_abort" --target-dir C:/temp/idf'


# $Env:RUST_BACKTRACE=1; \
# {{target-idf}} \
build *args:
	./export-esp.ps1; \
	$Env:RUST_BACKTRACE={{backtrace}}; \
	cargo build \
	--example {{args}} \

#remove speed if experiencing issues
# target-idf is causing stack overflows? possibly corrupt target dir
# {{target-idf}} \
flash *args:
	./export-esp.ps1; \
	cargo espflash {{port}} \
	--monitor \
	--release \
	--speed 921600 \
	--partition-table partitions.csv \
	--example {{args}}

# {{target-idf}} \
save *args:
	cargo espflash save-image \
	ESP32-C3 ./esp.image \
	--partition-table partitions.csv \
	--release \
	--merge \
	--example {{args}} \

monitor *args:
	cargo espflash serial-monitor {{port}} \
	--speed 921600