set windows-shell := ["C:/tools/cygwin/bin/sh.exe","-c"]

port := 'COM3'

# build:
# 	./export-esp.ps1 && cargo build --target riscv32imc-esp-espidf

flash file='forky_esp' *args='':
	cargo espflash {{port}} --monitor --release --bin {{file}} {{args}}

info:
	cargo espflash board-info {{port}}

monitor:
	cargo espflash serial-monitor {{port}}

watch command:
	cargo watch -q --ignore '**/mod.rs' -- {{command}}